apiVersion: apps/v1
kind: Deployment
metadata: 
  name: crud
  labels: 
    name: "crud"
    # force policy will ensure that deployment is updated
    # even when tag is unchanged (latest remains)
    keel.sh/policy: force
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: crud
  template:
    metadata:
      name: crud
      labels:
        app: crud
    spec:     
      containers:                    
        - image: lieroz/bmstu-dips:latest
          imagePullPolicy: Always # this is required to force pull image     
          name: crud
          env:
            - name: PORT
              value: "8080"
            - name: REDIS_HOST
              value: redis-master
            - name: REDIS_PORT
              value: "6379"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 5

---
apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: crud-service     # Unique name of the resource
spec:
  type: NodePort                 # Expose the Pods by opening a port on each Node and proxying it to the service.
  ports:                         # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
  - name: http
    port: 9090
    targetPort: 8080
  selector:
    app: crud            # Map any pod with label `app=go-redis-app` to this service
