language: rust
rust:
  - stable

sudo: required

services:
  - redis-server
  - docker

cache: cargo

script:
  - cargo build --verbose
  - cargo test --verbose

after_script:
  - docker build -t "$REGISTRY_USER"/bmstu-dips .

before_deploy:
  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
deploy:
  provider: script
  script: docker push "$REGISTRY_USER"/bmstu-dips
  on:
    branch: feature/lab-1
