language: rust
rust:
  - stable

sudo: required

services:
  - redis-server
  - docker

cache: cargo

script:
  - cargo build --verbose
  - cargo test --verbose

before_deploy:
  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker build -t "$REGISTRY_USER"/bmstu-dips:v1 .
deploy:
  provider: script
  script: docker push "$REGISTRY_USER"/bmstu-dips:v1
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|feature\/.+)$
