language: rust
rust:
  - stable

sudo: required

services:
  - redis-server
  - docker

cache: cargo

script:
  - cargo build --verbose
  - cargo test --verbose

after_script:
  - docker images
  - docker rmi -f $(docker images -a -q)
  - docker build -t lieroz/bmstu-dips .

before_deploy:
  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
deploy:
  provider: script
  script: docker push lieroz/bmstu-dips
  on:
    branch: feature/lab-1
